version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: mn-elasticsearch
    volumes:
      - ~/es-upgrade/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/es-upgrade/data:/usr/share/elasticsearch/data:z
      - ~/es-upgrade/snapshot:/mnt/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - mn_cd_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: mn-kibana
    volumes:
      - ~/es-upgrade/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    restart: always
    networks:
      - mn_cd_network
    depends_on:
      - elasticsearch

networks:
  mn_cd_network:
       driver: bridge
